version: '2'
services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/hosts:/etc/nginx/conf.d
            - /var/www:/var/www
            - /var/logs:/var/log/nginx
        links:
            - php
    php:
        # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
        build: /var/images/php
        # этот образ будет общаться с mysql
        links:
            - mysql
            - redis
            - rabbitmq
        # монтируем директорию с проектами
        volumes:
            - /var/www:/var/www
    mysql:
        image: mysql:5.7
        ports:
            - "3706:3306"
        volumes:
            - /var/mysql:/var/lib/mysql
        # задаем пароль для root пользователя
        environment:
            MYSQL_ROOT_PASSWORD: 123321
    redis:
        image: redis:latest
        command: redis-server --appendonly yes

    rabbitmq:
        image: rabbitmq:3.6.6
        container_name: rabbitmq_1
        environment:
              RABBITMQ_ERLANG_COOKIE: hash
              RABBITMQ_DEFAULT_USER: rabbitmq_user
              RABBITMQ_DEFAULT_PASS: 123321
              RABBITMQ_DEFAULT_VHOST: /
        ports:
            - "15672:15672"
            - "5672:5672"
        volumes:
            - /var/rabbitmq:/var/lib/rabbitmq
            - /var/logs/rabbitmq:/var/log/rabbitmq
            - /var/images/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
        restart: "always"

